services:
  api_app:
    build:
      context: ./api_app
      dockerfile: Dockerfile.api
    container_name: warehouse_api
    volumes:
      - ./common:/common:rw
    environment:
      PYTHONPATH: "/app:/common"
      # Carga automÃ¡ticamente variables del .env
    env_file:
      - ./api_app/.env
    ports:
      - "8000:8000"
    restart: always
    

  dash_app:
    build:
      context: ./dash_app
      dockerfile: Dockerfile.dash
    container_name: warehouse_dash
    volumes:
      - ./common:/common:ro
    environment:
      PYTHONPATH: "/app:/common"
      API_URL: "http://api_app:8000"
    ports:
      - "8050:8050"
    restart: always
    depends_on:  # ðŸ”¥ AÃ‘ADIR para orden de inicio
      - api_app
    